export const voiceVarientOptions = [
  { title: 'Non aktif', value: '0' },
  { title: '👩 🇮🇩 Indonesian A', value: '1' },
  { title: '👨 🇮🇩 Indonesian B', value: '2' },
  { title: '👨 🇮🇩 Indonesian C', value: '3' },
  { title: '👩 🇮🇩 Indonesian D', value: '4' },
  { title: '👩 🇭🇲 English A', value: '5' },
  { title: '👨 🇭🇲 English B', value: '6' },
  { title: '👩 🇭🇲 English C', value: '7' },
  { title: '👨 🇭🇲 English D', value: '8' },
  { title: '👩 🇬🇧 English A', value: '9' },
  { title: '👨 🇬🇧 English B', value: '10' },
  { title: '👩 🇬🇧 English C', value: '11' },
  { title: '👨 🇬🇧 English D', value: '12' },
  { title: '👩 🇬🇧 English F', value: '13' },
  { title: '👩 🇮🇳 English A', value: '14' },
  { title: '👨 🇮🇳 English B', value: '15' },
  { title: '👨 🇮🇳 English C', value: '16' },
  { title: '👩 🇮🇳 English D', value: '17' },
  { title: '👨 🇺🇸 English A', value: '18' },
  { title: '👨 🇺🇸 English B', value: '19' },
  { title: '👩 🇺🇸 English C', value: '20' },
  { title: '👨 🇺🇸 English D', value: '21' },
  { title: '👩 🇺🇸 English E', value: '22' },
  { title: '👩 🇺🇸 English F', value: '23' },
  { title: '👩 🇺🇸 English G', value: '24' },
  { title: '👩 🇺🇸 English H', value: '25' },
  { title: '👨 🇺🇸 English I', value: '26' },
  { title: '👨 🇺🇸 English J', value: '27' },
]

export const fontOptions = [
  { title: 'default', value: 'default' },
  { title: 'Roboto', value: 'Roboto' },
  { title: 'Open Sans', value: 'Open Sans' },
  { title: 'Lato', value: 'Lato' },
  { title: 'Montserrat', value: 'Montserrat' },
  { title: 'Source Sans Pro', value: 'Source Sans Pro' },
  { title: 'Oswald', value: 'Oswald' },
  { title: 'Poppins', value: 'Poppins' },
  { title: 'Noto Sans', value: 'Noto Sans' },
  { title: 'Raleway', value: 'Raleway' },
  { title: 'PT Sans', value: 'PT Sans' },
  { title: 'Merriweather', value: 'Merriweather' },
  { title: 'Playfair Display', value: 'Playfair Display' },
  { title: 'Nunito', value: 'Nunito' },
  { title: 'Rubik', value: 'Rubik' },
  { title: 'Lora', value: 'Lora' },
  { title: 'Mukta', value: 'Mukta' },
  { title: 'Work Sans', value: 'Work Sans' },
  { title: 'Nunito Sans', value: 'Nunito Sans' },
  { title: 'PT Serif', value: 'PT Serif' },
  { title: 'Nanum Gothic', value: 'Nanum Gothic' },
  { title: 'Hind Siliguri', value: 'Hind Siliguri' },
  { title: 'Inter', value: 'Inter' },
  { title: 'Noto Serif', value: 'Noto Serif' },
  { title: 'Titillium Web', value: 'Titillium Web' },
  { title: 'Quicksand', value: 'Quicksand' },
  { title: 'Heebo', value: 'Heebo' },
  { title: 'Karla', value: 'Karla' },
  { title: 'Barlow', value: 'Barlow' },
  { title: 'Inconsolata', value: 'Inconsolata' },
  { title: 'Oxygen', value: 'Oxygen' },
  { title: 'Source Code Pro', value: 'Source Code Pro' },
  { title: 'PT Sans Narrow', value: 'PT Sans Narrow' },
  { title: 'Josefin Sans', value: 'Josefin Sans' },
  { title: 'Arimo', value: 'Arimo' },
  { title: 'Dosis', value: 'Dosis' },
  { title: 'Libre Franklin', value: 'Libre Franklin' },
  { title: 'Anton', value: 'Anton' },
  { title: 'Cabin', value: 'Cabin' },
  { title: 'Libre Baskerville', value: 'Libre Baskerville' },
  { title: 'Mulish', value: 'Mulish' },
  { title: 'Hind', value: 'Hind' },
  { title: 'Bitter', value: 'Bitter' },
  { title: 'IBM Plex Sans', value: 'IBM Plex Sans' },
  { title: 'Crimson Text', value: 'Crimson Text' },
  { title: 'Dancing Script', value: 'Dancing Script' },
  { title: 'Lobster', value: 'Lobster' },
  { title: 'Abel', value: 'Abel' },
  { title: 'Varela Round', value: 'Varela Round' },
  { title: 'Fjalla One', value: 'Fjalla One' },
  { title: 'Cairo', value: 'Cairo' },
  { title: 'DM Sans', value: 'DM Sans' },
  { title: 'Source Serif Pro', value: 'Source Serif Pro' },
  { title: 'Yanone Kaffeesatz', value: 'Yanone Kaffeesatz' },
  { title: 'Arvo', value: 'Arvo' },
  { title: 'Kanit', value: 'Kanit' },
  { title: 'Bebas Neue', value: 'Bebas Neue' },
  { title: 'EB Garamond', value: 'EB Garamond' },
  { title: 'Teko', value: 'Teko' },
  { title: 'Zilla Slab', value: 'Zilla Slab' },
  { title: 'Indie Flower', value: 'Indie Flower' },
  { title: 'Prompt', value: 'Prompt' },
  { title: 'Exo 2', value: 'Exo 2' },
  { title: 'Pacifico', value: 'Pacifico' },
  { title: 'Architects Daughter', value: 'Architects Daughter' },
  { title: 'Shadows Into Light', value: 'Shadows Into Light' },
  { title: 'Questrial', value: 'Questrial' },
  { title: 'Merriweather Sans', value: 'Merriweather Sans' },
  { title: 'Asap', value: 'Asap' },
  { title: 'Hind Madurai', value: 'Hind Madurai' },
  { title: 'Slabo 27px', value: 'Slabo 27px' },
  { title: 'Balsamiq Sans', value: 'Balsamiq Sans' },
  { title: 'Overpass', value: 'Overpass' },
  { title: 'Cormorant Garamond', value: 'Cormorant Garamond' },
  { title: 'Archivo Narrow', value: 'Archivo Narrow' },
  { title: 'Abril Fatface', value: 'Abril Fatface' },
  { title: 'Assistant', value: 'Assistant' },
  { title: 'Maven Pro', value: 'Maven Pro' },
  { title: 'Antic Slab', value: 'Antic Slab' },
  { title: 'Caveat', value: 'Caveat' },
  { title: 'Exo', value: 'Exo' },
  { title: 'IBM Plex Serif', value: 'IBM Plex Serif' },
  { title: 'Rajdhani', value: 'Rajdhani' },
  { title: 'Martel', value: 'Martel' },
  { title: 'Play', value: 'Play' },
  { title: 'Domine', value: 'Domine' },
  { title: 'Bree Serif', value: 'Bree Serif' },
  { title: 'Amatic SC', value: 'Amatic SC' },
  { title: 'Catamaran', value: 'Catamaran' },
  { title: 'Fredoka One', value: 'Fredoka One' },
  { title: 'Righteous', value: 'Righteous' },
  { title: 'Acme', value: 'Acme' },
  { title: 'Alfa Slab One', value: 'Alfa Slab One' },
  { title: 'Signika', value: 'Signika' },
  { title: 'Satisfy', value: 'Satisfy' },
  { title: 'Tajawal', value: 'Tajawal' },
  { title: 'ABeeZee', value: 'ABeeZee' },
  { title: 'PT Sans Caption', value: 'PT Sans Caption' },
  { title: 'Cinzel', value: 'Cinzel' },
  { title: 'Manrope', value: 'Manrope' },
  { title: 'Archivo', value: 'Archivo' },
  { title: 'Nanum Myeongjo', value: 'Nanum Myeongjo' },
  { title: 'Patrick Hand', value: 'Patrick Hand' },
  { title: 'IBM Plex Mono', value: 'IBM Plex Mono' },
  { title: 'Viga', value: 'Viga' },
]
